name: Automatic Deployment

on:
  push:
    branches:
      - main


jobs:
  pages-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}


    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE